CREATE TABLE SRC_ABSENCES (
    id_absenta         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- cheie primara autonumerica
    id_angajat         NUMBER NOT NULL,            -- FK catre SRC_ANGAJAT
    nume_complet       VARCHAR2(100),              -- optional, pentru referinta rapida
    data_start         DATE NOT NULL,              -- prima zi de absenta
    data_sfarsit       DATE NOT NULL,              -- ultima zi de absenta
    zile               NUMBER(3),                  -- numar de zile de absenta
    motiv              VARCHAR2(50),               -- tipul absentei (medical, concediu, etc.)
    loading_timestamp  TIMESTAMP,                  -- cand s-a importat inregistrarea
    dataset_nume       VARCHAR2(50)                -- eticheta pentru batch-ul de import
);

-- Trigger care completeaza automat loading_timestamp si dataset_nume
CREATE OR REPLACE TRIGGER trg_set_metadata_absences
BEFORE INSERT ON SRC_ABSENCES
FOR EACH ROW
BEGIN
  :NEW.loading_timestamp := SYSTIMESTAMP;
  :NEW.dataset_nume := 'absences_' || TO_CHAR(SYSTIMESTAMP, 'DD-MM-YY');
END;
/


COMMIT;